#!/usr/bin/env python
"""
Gmail SMTP Setup for Trashmandu

This script helps you configure Gmail SMTP for sending emails.

STEPS:
1. Go to Google Account: https://myaccount.google.com/
2. Security Settings: https://myaccount.google.com/security
3. Enable "2-Step Verification" (if not already enabled)
4. Create an "App Password" (16-character password generated by Google)
5. Copy the app password and run this script to set up environment variables

For Windows PowerShell, run these commands:
$env:DJANGO_EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
$env:DJANGO_EMAIL_HOST = 'smtp.gmail.com'
$env:DJANGO_EMAIL_PORT = '587'
$env:DJANGO_EMAIL_USE_TLS = 'True'
$env:DJANGO_EMAIL_HOST_USER = 'anupshrestha865@gmail.com'
$env:DJANGO_EMAIL_HOST_PASSWORD = 'YOUR_APP_PASSWORD_HERE'
$env:DJANGO_DEFAULT_FROM_EMAIL = 'anupshrestha865@gmail.com'

Then restart your Django server with: python manage.py runserver

For Linux/Mac, add to ~/.bashrc or ~/.zshrc:
export DJANGO_EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
export DJANGO_EMAIL_HOST='smtp.gmail.com'
export DJANGO_EMAIL_PORT='587'
export DJANGO_EMAIL_USE_TLS='True'
export DJANGO_EMAIL_HOST_USER='anupshrestha865@gmail.com'
export DJANGO_EMAIL_HOST_PASSWORD='YOUR_APP_PASSWORD_HERE'
export DJANGO_DEFAULT_FROM_EMAIL='anupshrestha865@gmail.com'

Then restart your shell: source ~/.bashrc
"""

import os
import sys

print(__doc__)

# Quick test
if __name__ == "__main__":
    email = os.environ.get('DJANGO_EMAIL_HOST_USER', '')
    if email:
        print(f"\n✓ Email configured: {email}")
    else:
        print("\n✗ Email not configured yet. Follow the steps above.")
