# Generated by Django 5.1.3 on 2025-06-25 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
