# Generated by Django 5.1.3 on 2025-06-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='phone',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
