# Generated by Django 5.1.3 on 2025-11-10 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='verification_code',
        ),
    ]
