# Generated by Django 5.1.3 on 2025-11-10 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectorapp', '0008_remove_collectorprofile_email_verified_and_more'),
        ('userapp', '0012_userprofile_reset_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlasticType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True)),
                ('recyclable', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pickuprequest',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='pickuprequest',
            name='weight',
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='assigned_collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collectorapp.collectorprofile'),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='PlasticItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('price_at_time', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pickup_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.pickuprequest')),
                ('plastic_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userapp.plastictype')),
            ],
        ),
    ]
