# Generated by Django 5.1.3 on 2025-06-11 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectorapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorprofile',
            name='total_pickups',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='collectorprofile',
            name='total_waste_collected',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='collectorprofile',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='collectorprofile',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='PickupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('location', models.CharField(max_length=255)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('assigned_collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collector_pickup_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
