# Generated by Django 5.1.3 on 2025-11-15 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collectorapp', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
