# Generated by Django 5.1.3 on 2025-06-24 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collectorapp', '0004_remove_pickuprequest_collector_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PickupRequest',
        ),
    ]
