# Generated by Django 5.2.8 on 2025-11-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectorapp', '0004_collectorprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectorprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='collectorprofile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='collectorprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectorprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='collectorprofile',
            name='citizenship_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
