# Generated by Django 5.1.3 on 2025-06-25 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectorapp', '0005_delete_pickuprequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectorprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='collectorprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='collectorprofile',
            name='total_pickups',
        ),
        migrations.RemoveField(
            model_name='collectorprofile',
            name='total_waste_collected',
        ),
        migrations.AddField(
            model_name='collectorprofile',
            name='citizenship_id',
            field=models.CharField(blank=True, default='NA', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='collectorprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectorprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collectorprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter a valid 10-digit phone number')]),
        ),
        migrations.AddField(
            model_name='collectorprofile',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
