# Generated by Django 5.2.8 on 2025-11-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectorapp', '0005_remove_collectorprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectorprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='collectorprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='collectorprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectorprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='collectorprofile',
            name='citizenship_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='collectorprofile',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
