# Generated by Django 5.1.3 on 2025-06-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectorapp', '0006_remove_collectorprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectorprofile',
            name='citizenship_id',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='collectorprofile',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='collectorprofile',
            name='phone_number',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='collectorprofile',
            name='verification_code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
