# Generated by Django 5.1.3 on 2025-11-10 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collectorapp', '0007_alter_collectorprofile_citizenship_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectorprofile',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='collectorprofile',
            name='verification_code',
        ),
    ]
